### ISSUE TITLE
How to install LoraPacketForwarder

### ISSUE THREAD

**Issue by batsuurib** [zhgzhg/LoRaPacketForwarder#13]
Hello,

How to install LoraPacketForarder? How make linux service.

**Comment by zhgzhg** [comment]
Hi @batsuurib ,
I've added a sample service file - LoRaPktFwrd.service 

Before installing it make sure you have a working `config.json` file in the directory of the project.

To install the service you can execute:
```
make
sudo make install
```

To allow the service to run automatically after the system boots:
`sudo systemctl enable LoRaPktFwrd.service`

To manually start / stop / restart the service:

`sudo service LoRaPktFwrd start`
`sudo service LoRaPktFwrd restart`
`sudo service LoRaPktFwrd stop`

Please let me know if the above works for you. Thanks!

**Comment by batsuurib** [comment]
thank you very much
