### ISSUE TITLE
SPI Fail on OrangePi Zero 2

### ISSUE THREAD

**Issue by loratrak** [zhgzhg/LoRaPacketForwarder#9]
Hi,

I'm using a OrangePi Zero2 board and wiringPi already installed, with gpio readall command working. See bellow

![image](https://user-images.githubusercontent.com/105125894/171322337-0ad819e1-3be3-4018-b6c7-efc8dfe92d7e.png)

But when I tried to start, you can see this error bellow:

![image](https://user-images.githubusercontent.com/105125894/171322586-96c635a7-3d9c-4b0c-8e5b-c57eb044f242.png)

In config.json I tried to set SPI channel to 1 but SPI don't open.

![image](https://user-images.githubusercontent.com/105125894/171322764-44fa020d-7dd9-42a2-830d-b29118559e27.png)

I think is everything is ok with my SPI, I tested with gpio write

![image](https://user-images.githubusercontent.com/105125894/171322891-cb62d2ac-8ce9-4632-b23d-4c972e79abb6.png)

![image](https://user-images.githubusercontent.com/105125894/171322954-681006c5-f727-4537-8e23-9cc272c1dded.png)

Thanks in advance with you have any idea of the issue.

**Comment by zhgzhg** [comment]
Hi @loratrak , error 65534 indicates the SPI communication is not happening. Can you double check your hardware setup, especially the MISO, MOSI, and CS pins. If you have them wrongly connected to the OrangePi Zero 2 pins this error usually arises.


Edit: Btw spidev1.1 looks the correct choice. You can also check for connected in reverse MISO and MOSI pins.

**Comment by loratrak** [comment]
Hi @zhgzhg,
I doubled checked hw pins, and are correct. I tried reversed MISO & MOSI pins and didn't work. I'm using these pins to MISO, MOSI and CS.

![image](https://user-images.githubusercontent.com/105125894/171483674-d9af2a3d-f072-413e-8945-bdffd9777f7a.png)

I have a RPB1 with the same lora hat, and I have to change the channel to 1 and it worked. But in OrangePi the channel 1 didn't work and I don't know why.

Thanks

**Comment by zhgzhg** [comment]
Can you try [https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#loopback-test](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html#loopback-test) just to see if your SPI channels work. If they do perhaps there could be some issue with the wiringPi library not properly supporting the Zero 2 board.

**Comment by loratrak** [comment]
It's working with loopback tests, on /dev/spidev1.1

![image](https://user-images.githubusercontent.com/105125894/171521425-429d2264-184a-49f0-b427-69304f546457.png)

**Comment by zhgzhg** [comment]
Thanks, I think I understand what's happening - the packet forwarder is attempting to open the incorrect SPI device, because of `spidev*.*` naming differences for OrangePi Zero 2. This is because it's relying on wiringPi's default naming convention for SPI devices.

I'll make the config.json file to support specifying both **channel** and **port** i.e. "spidev<**channelNumber**>.<**portNumer**>" which if I am right should resolve the issue.

Until then as a temporary workaround can you please try creating symlinks to your existing devices:

` ln -s /dev/spidev1.0 /dev/spidev1.1`

the above will create a "virtual" spi port "0" redirecting to the real port "1".

**Comment by loratrak** [comment]
I ran this "ln -s /dev/spidev1.1 /dev/spidev1.0" and it's working right now

![image](https://user-images.githubusercontent.com/105125894/171678724-3cf0f5ed-0e38-4c5c-bf39-8ebb03ef4123.png)

![image](https://user-images.githubusercontent.com/105125894/171678862-4224608f-0ed7-4163-b84f-40db5a781285.png)

Thanks a lot!!!
